model_name_or_path: PLACEHOLDER_MODEL_NAME_OR_PATH

# GPU memory: 8 * 78GB
do_train: true
stage: sft
finetuning_type: full # only support full for now
dataset: PLACEHOLDER_DATASET
preprocessing_num_workers: 32
cutoff_len: 24576
template: qwen3_5
tokenized_path: PLACEHOLDER_TOKENIZED_DATASET_PATH

# global batchsize = (8 // 2 // 4) * 8 = 8
output_dir: PLACEHOLDER_OUTPUT_DIR
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
num_train_epochs: 1.0
learning_rate: 3e-6
logging_steps: 10
save_steps: 500
lr_scheduler_type: constant
bf16: true

# mcore speed up
tensor_model_parallel_size: 1
sequence_parallel: false
pipeline_model_parallel_size: 4
bias_activation_fusion: true
apply_rope_fusion: false
use_distributed_optimizer: true
overlap_param_gather: true
overlap_grad_reduce: true
moe_grouped_gemm: true
moe_token_dispatcher_type: alltoall
expert_model_parallel_size: 2
recompute_granularity: full
